apiVersion: apps/v1
kind: Deployment
metadata:
  name: AmazonApp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AmazonApp
  template:
    metadata:
      labels:
        app: AmazonApp
    spec:
      containers:
        - name: AmazonApp
          image: abdelrhmanh21/amazon-devsecops:1.0.0-5
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
